GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
"name": "Kehidupan", "notes": "Sakitttnyaaaa"
}

### 

PATCH  http://localhost:3000/users/1 
Content-Type: application/json

{
"name": "ehmasa", "notes": "hah"
}

###

DELETE http://localhost:3000/users/1